# Generated by Django 4.2.6 on 2023-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('name', models.CharField(max_length=250)),
                ('student_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('semester', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('maritalStatus', models.CharField(max_length=150, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('comment', models.TextField()),
            ],
        ),
    ]
