# Generated by Django 4.1.7 on 2023-10-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='c_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
