# Generated by Django 4.2.6 on 2023-10-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_signup_c_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='media/')),
                ('about_title', models.CharField(max_length=120)),
                ('about_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_id', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=80)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
