# Generated by Django 4.2.6 on 2023-10-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cse_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_cse',
            old_name='name',
            new_name='cse_category',
        ),
        migrations.RenameField(
            model_name='cse',
            old_name='category',
            new_name='cse_category',
        ),
    ]
