# Generated by Django 4.2.6 on 2023-10-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_name_category_cse_cse_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Bba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bba_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Eee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eee_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Eng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_img', models.ImageField(upload_to='media/pharmacy/')),
                ('pharmacy_book', models.CharField(max_length=150)),
                ('pharmacy_teacher', models.CharField(max_length=120)),
                ('pharmacy_file', models.FileField(upload_to='media/pharmacy/')),
                ('pharmacy_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category_pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_img', models.ImageField(upload_to='media/law/')),
                ('law_book', models.CharField(max_length=150)),
                ('law_teacher', models.CharField(max_length=120)),
                ('law_file', models.FileField(upload_to='media/law/')),
                ('law_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category_law')),
            ],
        ),
        migrations.CreateModel(
            name='Eng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_img', models.ImageField(upload_to='media/eng/')),
                ('eng_book', models.CharField(max_length=150)),
                ('eng_teacher', models.CharField(max_length=120)),
                ('eng_file', models.FileField(upload_to='media/eng/')),
                ('eng_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category_eng')),
            ],
        ),
        migrations.CreateModel(
            name='Eee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eee_img', models.ImageField(upload_to='media/eee/')),
                ('eee_book', models.CharField(max_length=150)),
                ('eee_teacher', models.CharField(max_length=120)),
                ('eee_file', models.FileField(upload_to='media/eee/')),
                ('eee_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category_eee')),
            ],
        ),
        migrations.CreateModel(
            name='Civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_img', models.ImageField(upload_to='media/civil/')),
                ('civil_book', models.CharField(max_length=150)),
                ('civil_teacher', models.CharField(max_length=120)),
                ('civil_file', models.FileField(upload_to='media/civil/')),
                ('civil_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category_civil')),
            ],
        ),
        migrations.CreateModel(
            name='Bba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bba_img', models.ImageField(upload_to='media/bba/')),
                ('bba_book', models.CharField(max_length=150)),
                ('bba_teacher', models.CharField(max_length=120)),
                ('bba_file', models.FileField(upload_to='media/bba/')),
                ('bba_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.category_bba')),
            ],
        ),
    ]
