# Generated by Django 4.2.6 on 2023-11-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_bba_category_civil_category_eee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_image', models.ImageField(upload_to='media/mission')),
                ('mission_title', models.CharField(max_length=120)),
                ('mission_desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bba',
            name='bba_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bba',
            name='bba_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='civil',
            name='civil_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='civil',
            name='civil_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cse',
            name='cse_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cse',
            name='cse_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eee',
            name='eee_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eee',
            name='eee_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eng',
            name='eng_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eng',
            name='eng_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='law_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='law_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(upload_to='media/about'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.FileField(upload_to='media/signup'),
        ),
    ]
