# Generated by Django 4.2.6 on 2023-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_bba_bba_comment_remove_civil_civil_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='media/team')),
                ('team_title', models.CharField(max_length=120)),
                ('team_desc', models.TextField()),
            ],
        ),
    ]
